FROM ubuntu:20.04 as stage1

ARG CURL_COMMIT=d755a5f7c009dd63a61b2c745180d8ba937cbfeb
ARG BORINGSSL_COMMIT=1c7d52ef3e3f373302cb957089fa783d1e5fd8cd
ARG NGHTTP2_COMMIT=05b792901933664e7aeb7ebb8c87db81123d484a
ARG NGTCP2_COMMIT=843aa72100b508e192f119439a943028b0c6f030
ARG NGHTTP3_COMMIT=868e81b343d1350597b47f78a5958d60c3695aa4
ARG ZLIB_COMMIT=04f42ceca40f73e2978b50e93806c2a18c1281fc
ARG ZSTD_COMMIT=a58b48ef0e543980888a4d9d16c9072ff22135ca
ARG BROTLI_COMMIT=71fe6cac061ac62c0241f410fbd43a04a6b4f303

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN sed -i 's@archive.ubuntu.com@mirrors.aliyun.com@g; s@security.ubuntu.com@mirrors.aliyun.com@g' /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y build-essential

RUN apt-get install -y curl golang ninja-build

ARG CMAKE_VERSION=3.22.6

RUN curl -L -k https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.sh -o /tmp/cmake-install.sh && \
    chmod +x /tmp/cmake-install.sh && \
    /tmp/cmake-install.sh --skip-license --prefix=/usr/local && \
    rm -f /tmp/cmake-install.sh

RUN curl -L https://github.com/google/brotli/archive/${BROTLI_COMMIT}.tar.gz -o brotli-${BROTLI_COMMIT}.tar.gz && \
    tar -xf brotli-${BROTLI_COMMIT}.tar.gz

RUN cd brotli-${BROTLI_COMMIT} && \
    mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./installed -DBUILD_SHARED_LIBS=0 .. && \
    cmake --build . --config Release --target install

RUN curl -L https://github.com/facebook/zstd/archive/${ZSTD_COMMIT}.tar.gz -o zstd-${ZSTD_COMMIT}.tar.gz && \
    tar -xf zstd-${ZSTD_COMMIT}.tar.gz

RUN cd zstd-${ZSTD_COMMIT} && \
    cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./installed ./cmake && \
    cmake --build . --config Release --target install

RUN curl -L https://github.com/madler/zlib/archive/${ZLIB_COMMIT}.tar.gz -o zlib-${ZLIB_COMMIT}.tar.gz && \
    tar -xf zlib-${ZLIB_COMMIT}.tar.gz

RUN cd zlib-${ZLIB_COMMIT} && \
    mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./installed .. && \
    cmake --build . --config Release --target install

RUN curl -L https://github.com/nghttp2/nghttp2/archive/${NGHTTP2_COMMIT}.tar.gz -o nghttp2-${NGHTTP2_COMMIT}.tar.gz && \
    tar -xf nghttp2-${NGHTTP2_COMMIT}.tar.gz

RUN cd nghttp2-${NGHTTP2_COMMIT} && \
    mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./installed -DENABLE_SHARED_LIB=0 -DENABLE_STATIC_LIB=1 .. && \
    cmake --build . --config Release --target install

RUN curl -L https://github.com/google/boringssl/archive/${BORINGSSL_COMMIT}.tar.gz -o boringssl-${BORINGSSL_COMMIT}.tar.gz && \
    tar -xf boringssl-${BORINGSSL_COMMIT}.tar.gz

COPY boringssl-${BORINGSSL_COMMIT}.patch boringssl-${BORINGSSL_COMMIT}/

RUN cd boringssl-${BORINGSSL_COMMIT} && \
    patch -p1 < boringssl-${BORINGSSL_COMMIT}.patch

RUN cd boringssl-${BORINGSSL_COMMIT} && \
    mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF  -DBENCHMARK_ENABLE_TESTING=OFF -DCMAKE_INSTALL_PREFIX=./installed -DBUILD_SHARED_LIBS=0 -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=./lib -DCMAKE_POSITION_INDEPENDENT_CODE=1 -GNinja .. && \
    ninja ssl crypto

RUN cp -R boringssl-${BORINGSSL_COMMIT}/include boringssl-${BORINGSSL_COMMIT}/build

RUN curl -L https://github.com/ngtcp2/nghttp3/archive/${NGHTTP3_COMMIT}.tar.gz -o nghttp3-${NGHTTP3_COMMIT}.tar.gz && \
    tar -xf nghttp3-${NGHTTP3_COMMIT}.tar.gz

ARG SFPARSE_COMMIT=4b313cfd2e1b389ae632b36dcd50402307289af2

RUN mkdir -p nghttp3-${NGHTTP3_COMMIT}/lib/sfparse && \
    curl -L https://github.com/ngtcp2/sfparse/archive/${SFPARSE_COMMIT}.tar.gz -o /tmp/sfparse.tar.gz && \
    tar -xzf /tmp/sfparse.tar.gz --strip-components=1 -C nghttp3-${NGHTTP3_COMMIT}/lib/sfparse


COPY nghttp3-${NGHTTP3_COMMIT}.patch nghttp3-${NGHTTP3_COMMIT}/
RUN cd nghttp3-${NGHTTP3_COMMIT} && \
    patch -p1 < nghttp3-${NGHTTP3_COMMIT}.patch && \
    mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=1 -DCMAKE_INSTALL_PREFIX=./installed -DENABLE_SHARED_LIB=0 -DENABLE_STATIC_LIB=1 -DENABLE_LIB_ONLY=1 -DBUILD_TESTING=OFF .. && \
    cmake --build . --config Release --target install

RUN curl -L https://github.com/ngtcp2/ngtcp2/archive/${NGTCP2_COMMIT}.tar.gz -o ngtcp2-${NGTCP2_COMMIT}.tar.gz && \
    tar -xf ngtcp2-${NGTCP2_COMMIT}.tar.gz


COPY ngtcp2-${NGTCP2_COMMIT}.patch ngtcp2-${NGTCP2_COMMIT}/
RUN cd ngtcp2-${NGTCP2_COMMIT} && \
    patch -p1 < ngtcp2-${NGTCP2_COMMIT}.patch && \
    mkdir build && cd build && \
    cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_POSITION_INDEPENDENT_CODE=1 -DCMAKE_INSTALL_PREFIX=./installed \
    -DENABLE_SHARED_LIB=0 -DENABLE_STATIC_LIB=1 \
    -DENABLE_LIB_ONLY=1 \
    -DENABLE_OPENSSL=0 \
    -DENABLE_BORINGSSL=1 \
    -DBUILD_TESTING=OFF \
    -DBORINGSSL_INCLUDE_DIR=/boringssl-${BORINGSSL_COMMIT}/build/include \
    -DBORINGSSL_LIBRARIES="/boringssl-${BORINGSSL_COMMIT}/build/lib/libssl.a;/boringssl-${BORINGSSL_COMMIT}/build/lib/libcrypto.a;stdc++;pthread" \
    .. && \
    cmake --build . --config Release --target install

RUN curl -L https://github.com/curl/curl/archive/${CURL_COMMIT}.tar.gz -o curl-${CURL_COMMIT}.tar.gz && \
    tar -xf curl-${CURL_COMMIT}.tar.gz

COPY curl-${CURL_COMMIT}.patch curl-${CURL_COMMIT}/

RUN cd curl-${CURL_COMMIT} && \
    patch -p1 < curl-${CURL_COMMIT}.patch


RUN cd curl-${CURL_COMMIT} && \
    mkdir build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=./installed \
    -DBUILD_SHARED_LIBS=0 \
    -DCMAKE_BUILD_TYPE=Release \
    -DOPENSSL_ROOT_DIR=/boringssl-${BORINGSSL_COMMIT}/build/ \
    -DHAVE_SSL_CTX_SET_QUIC_METHOD=1 \
    -DZLIB_INCLUDE_DIR=/zlib-${ZLIB_COMMIT}/build/installed/include \
    -DZLIB_LIBRARY=/zlib-${ZLIB_COMMIT}/build/installed/lib/libz.a \
    -DUSE_NGHTTP2=1 \
    -DNGHTTP2_INCLUDE_DIR=/nghttp2-${NGHTTP2_COMMIT}/build/installed/include \
    -DNGHTTP2_LIBRARY=/nghttp2-${NGHTTP2_COMMIT}/build/installed/lib/libnghttp2.a \
    -DUSE_NGTCP2=1 \
    -DNGTCP2_INCLUDE_DIR=/ngtcp2-${NGTCP2_COMMIT}/build/installed/include \
    -DNGTCP2_LIBRARY=/ngtcp2-${NGTCP2_COMMIT}/build/installed/lib/libngtcp2.a \
    -Dngtcp2_crypto_boringssl_LIBRARY=/ngtcp2-${NGTCP2_COMMIT}/build/installed/lib/libngtcp2_crypto_boringssl.a \
    -DNGHTTP3_INCLUDE_DIR=/nghttp3-${NGHTTP3_COMMIT}/build/installed/include \
    -DNGHTTP3_LIBRARY=/nghttp3-${NGHTTP3_COMMIT}/build/installed/lib/libnghttp3.a \
    -DCURL_ZSTD=1 \
    -DZstd_INCLUDE_DIR=/zstd-${ZSTD_COMMIT}/build/installed/include \
    -DZstd_LIBRARY=/zstd-${ZSTD_COMMIT}/build/installed/lib/libzstd.a \
    -DCURL_BROTLI=1 \
    -DBROTLI_INCLUDE_DIR=/brotli-${BROTLI_COMMIT}/build/installed/include \
    -DBROTLIDEC_LIBRARY=/brotli-${BROTLI_COMMIT}/build/installed/lib/libbrotlidec.a \
    -DBROTLICOMMON_LIBRARY=/brotli-${BROTLI_COMMIT}/build/installed/lib/libbrotlicommon.a \
    -DENABLE_WEBSOCKETS=1 \
    -DBUILD_CURL_EXE=0 \
    -DCMAKE_POSITION_INDEPENDENT_CODE=1 \
    CFLAGS="-I/boringssl-${BORINGSSL_COMMIT}/build" \
    .. && \
    make libcurl_static && make install

RUN mkdir dist && \
    cp /curl-${CURL_COMMIT}/build/installed/lib/libcurl.a /dist && \
    cp /zstd-${ZSTD_COMMIT}/build/installed/lib/libzstd.a /dist && \
    cp /ngtcp2-${NGTCP2_COMMIT}/build/installed/lib/libngtcp2.a /dist && \
    cp /ngtcp2-${NGTCP2_COMMIT}/build/installed/lib/libngtcp2_crypto_boringssl.a /dist && \
    cp /nghttp3-${NGHTTP3_COMMIT}/build/installed/lib/libnghttp3.a /dist && \
    cp /boringssl-${BORINGSSL_COMMIT}/build/lib/libcrypto.a /dist && \
    cp /boringssl-${BORINGSSL_COMMIT}/build/lib/libssl.a /dist


FROM ubuntu:20.04 as stage2

COPY --from=stage1 /dist /curl-dist

CMD cp /curl-dist/* /output

